const app = document.querySelector("#app"),
  dialog = document.querySelector("#editor");
const icons = {
  overview: "M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z",
  transactions: "M4 7h16 M4 12h16 M4 17h10",
  budgets: "M4 4h16v16H4z M8 8h8 M8 12h3 M8 16h6",
  connections: "M8 12h8 M9 6H6a4 4 0 0 0 0 8h3 M15 10h3a4 4 0 0 1 0 8h-3",
  chat: "M20 11a8 8 0 0 1-8 8H5l-3 3V11a9 9 0 0 1 18 0z M7 10h8 M7 14h5",
  arrow: "M5 12h14 M13 6l6 6-6 6",
  up: "M6 16L18 4 M8 4h10v10",
  down: "M6 8l12 12 M8 20h10V10",
  shield: "M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6z M8 12l3 3 5-6",
  close: "M6 6l12 12 M6 18L18 6",
  wallet: "M3 6h16v4 M3 6v14h18V10H3 M16 14h5",
  spark: "M12 3l3 6 6 3-6 3-3 6-3-6-6-3 6-3z",
};
const icon = (name) =>
  `<svg class="icon" aria-hidden="true" viewBox="0 0 24 24"><path d="${icons[name] || icons.wallet}"/></svg>`;
const escape = (value) =>
  String(value ?? "").replace(
    /[&<>"']/g,
    (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        c
      ],
  );
const localMonth = () => {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
};
let selectedMonth = localMonth(),
  page = "overview",
  state = null,
  messages = [],
  conversations = [],
  activeConversation = null,
  conversationBefore = null,
  conversationNext = null,
  historyArchived = false,
  historyOpen = false,
  chatDrafts = {},
  historyTimer,
  noticeTimer,
  chatBusy = false,
  chatEpoch = 0;
const money = (value) =>
  new Intl.NumberFormat(undefined, {
    style: "currency",
    currency: state?.currency || "USD",
    maximumFractionDigits: 2,
  }).format(value / 100);
const monthTitle = () =>
  new Intl.DateTimeFormat(undefined, { month: "long", year: "numeric" }).format(
    new Date(`${selectedMonth}-02T12:00:00`),
  );
function notice(value) {
  document.querySelector("#notice").textContent = value;
  clearTimeout(noticeTimer);
  noticeTimer = setTimeout(() => {
    document.querySelector("#notice").textContent = "";
  }, 6500);
}
async function api(path, method = "GET", data) {
  const response = await fetch(path, {
    method,
    headers: method === "GET" ? {} : { "Content-Type": "application/json" },
    ...(data ? { body: JSON.stringify(data) } : {}),
  });
  const result = await response.json();
  if (!response.ok) {
    if (response.status === 401 && path != "/api/login") {
      state = null;
      clearChat();
      await loginScreen();
    }
    throw new Error(result.error || "Something went wrong");
  }
  return result;
}
async function load() {
  state = await api(`/api/state?month=${encodeURIComponent(selectedMonth)}`);
  render();
}
function brand() {
  return '<div class="brand"><img src="/logo.svg" alt=""/><span>BAS<small>BUDGET AUTOMATION STUDIO</small></span></div>';
}
function installGuide() {
  return `<details class="install-guide card"><summary>Add to your phone’s Home Screen</summary><p>Open your own secure, phone-accessible app address first. The computer-only demo address cannot open this workspace on a phone.</p><h3>iPhone · Safari</h3><ol><li>Open the app in Safari and tap Share.</li><li>Choose Add to Home Screen.</li><li>Keep Open as Web App on, name it BAS, then tap Add.</li></ol><h3>Android · Chrome</h3><ol><li>Open the app in Chrome and tap the three-dot menu.</li><li>Choose Install and create shortcut → Install, or Add to Home screen → Install.</li><li>Confirm, then open BAS from your Home Screen.</li></ol><p>You may need to sign in again. The app needs a connection to its server; adding an icon does not make it work offline.</p></details>`;
}
async function loginScreen() {
  const session = await api("/api/session");
  app.innerHTML = `<main id="main" class="login">${brand()}<h1>Find your<br>financial flow.</h1><p>Your money, in your element. An open-source studio for the budget you want to build.</p><form id="login-form"><label for="password">${session.mode === "demo" ? "Demo password" : "Your local password"}<input id="password" name="password" type="password" autocomplete="current-password" required ${session.mode === "demo" ? 'value="demo"' : ""}></label><button class="primary" type="submit">${session.mode === "demo" ? "Explore the demo" : "Open your budget"} →</button><p id="login-error" role="alert" class="dialog-error"></p></form><p class="note">${session.mode === "demo" ? "Synthetic data only. Demo password: demo. No bank connection or API key needed." : "Use the password generated by npm run setup. This instance stores data on your computer."}</p>${installGuide()}</main>`;
}
const nav = [
  ["overview", "Home"],
  ["transactions", "Activity"],
  ["budgets", "Budgets"],
  ["connections", "Connect"],
  ["chat", "Ask BAS"],
];
function render() {
  const focused = document.activeElement;
  const restoreComposer = focused?.matches("#chat-form textarea");
  const selection = restoreComposer
    ? [focused.selectionStart, focused.selectionEnd]
    : null;

  if (!state) return;
  app.innerHTML = `<div class="shell"><aside class="sidebar">${brand()}<nav class="nav" aria-label="Main navigation">${nav.map(([id, label]) => `<button data-page="${id}" class="${id === page ? "active" : ""}" ${id === page ? 'aria-current="page"' : ""}>${icon(id)}<span>${label}</span></button>`).join("")}</nav><div class="sidebar-foot">${icon("shield")}<strong>Your budget. Your control.</strong><p>Local storage, open source, and connections you choose.</p></div></aside><div class="workspace"><header class="topbar"><span class="breadcrumbs">Your workspace / ${nav.find((n) => n[0] === page)[1]}</span><div class="top-actions"><span class="badge">${state.mode === "demo" ? "Synthetic demo" : "Personal workspace"}</span><button class="ghost small" data-action="logout">Sign out</button><span class="avatar" aria-hidden="true">BAS</span></div></header><main id="main" tabindex="-1"><div class="page-head">${page === "overview" ? '<h1 class="sr-only">Home</h1>' : `<div><div class="page-eyebrow">${"YOUR STUDIO / " + escape(nav.find((n) => n[0] === page)[1].toUpperCase())}</div><h1>${{ transactions: "Every transaction, in view.", budgets: "A plan that fits your life.", connections: "Bring it all together.", chat: "A little help with the numbers." }[page]}</h1><p>${{ transactions: "Review, categorize, and keep the details organized.", budgets: "Set your priorities. Adjust as life happens.", connections: "Connect the services you choose, with your own keys.", chat: "Ask about the month you’re looking at." }[page]}</p></div>`}<label class="month-label" for="month">YOUR BUDGET MONTH<input type="month" id="month" value="${selectedMonth}" required></label></div>${{ overview: overview, transactions: transactions, budgets: budgets, connections: connections, chat: chat }[page]()}<p class="footer-note">${state.mode === "demo" ? "All figures are invented demo data. " : ""}One currency per workspace · ${escape(state.currency)} · Posted transactions only in totals · ${state.summary.unreviewed_count} awaiting review</p></main></div></div>`;
  if (restoreComposer) {
    const composer = document.querySelector("#chat-form textarea");
    if (composer && !composer.disabled) {
      composer.focus({ preventScroll: true });
      composer.setSelectionRange(...selection);
    }
  }
}
function budgetRows() {
  const categories = state.summary.categories.filter((c) => c.limit_cents > 0);
  return categories.length
    ? categories
        .map(
          (c) =>
            `<div class="budget-row ${c.spent_cents > c.limit_cents ? "over" : ""}"><div class="budget-meta"><strong>${escape(c.name)}</strong><span>${money(c.spent_cents)} / ${money(c.limit_cents)}</span></div><progress aria-label="${escape(c.name)} budget used" max="${c.limit_cents}" value="${Math.max(0, c.spent_cents)}"></progress><small>${c.remaining_cents >= 0 ? `${money(c.remaining_cents)} left` : `${money(-c.remaining_cents)} over budget`}</small></div>`,
        )
        .join("")
    : '<p class="empty">Give your money a plan.<br>Add your first monthly budget.</p>';
}
function txnList(rows, editable = false) {
  return rows.length
    ? rows
        .map(
          (t) =>
            `<div class="txn"><span class="txn-icon">${icon(t.amount_cents < 0 ? "down" : "wallet")}</span><div><strong>${escape(t.description)}</strong><small>${escape(t.date)} · ${escape(state.categories.find((c) => c.id === t.category_id)?.name || "Uncategorized")}${!t.reviewed ? " · Needs review" : ""}</small>${editable ? `<label class="sr-only" for="cat-${escape(t.id)}">Category for ${escape(t.description)}</label><select id="cat-${escape(t.id)}" data-transaction="${escape(t.id)}">${categoryOptions(t.category_id)}</select>${!t.reviewed ? `<button class="small ghost" data-review="${escape(t.id)}" data-category="${escape(t.category_id)}">Confirm category</button>` : ""}` : ""}</div><div class="amount ${t.amount_cents < 0 ? "income" : ""}">${t.amount_cents < 0 ? "+" : "−"}${money(Math.abs(t.amount_cents))}${t.pending ? '<small class="pending">Pending · excluded</small>' : ""}</div></div>`,
        )
        .join("")
    : '<p class="empty">No transactions this month.<br>Add one manually or connect a provider.</p>';
}
function overview() {
  const s = state.summary;
  return `<div class="dashboard-grid"><div><section class="hero" aria-labelledby="net-heading"><div class="hero-top"><div><h2 class="eyebrow" id="net-heading">NET CASH FLOW · ${escape(monthTitle())}</h2><div class="big">${money(s.net_cents)}</div><p>Income minus spending, after refunds.</p></div></div><div class="flow-metrics"><div><span>Money in</span><strong>${money(s.income_cents)}</strong></div><div><span>Money out</span><strong>${money(s.spent_cents)}</strong></div></div><div class="hero-bottom"><span><strong>${money(s.budget_cents)}</strong> planned</span><span>${s.pending_count} pending · excluded</span></div></section>${s.unreviewed_count ? `<button class="review-callout" data-page="transactions"><span class="review-count">${s.unreviewed_count}</span><span><strong>A little review. A clearer picture.</strong><small>Confirm categories to keep your totals useful.</small></span>${icon("arrow")}</button>` : ""}<section class="card section-gap activity-card"><div class="card-head"><h2>Recent activity</h2><button class="small ghost" data-page="transactions">View all →</button></div>${txnList(state.transactions.slice(0, 5))}</section></div><div class="stack"><section class="card"><div class="card-head"><h2>Your monthly plan</h2><button class="small ghost" data-page="budgets">Edit →</button></div>${budgetRows()}</section><section class="card helper-card"><div class="helper-icon">${icon("spark")}</div><h2>A clearer view<br>starts with a question.</h2><p>Explore the numbers behind your month with your own budget assistant.</p><button data-page="chat">Ask BAS →</button></section></div></div>`;
}
function categoryOptions(selected = "uncategorized") {
  return state.categories
    .map(
      (c) =>
        `<option value="${escape(c.id)}" ${selected === c.id ? "selected" : ""}>${escape(c.name)}</option>`,
    )
    .join("");
}
function transactions() {
  return `<section class="card wide"><div class="filter-row"><label class="search"><span class="sr-only">Search transactions</span><input id="search" placeholder="Search description or category…" type="search"></label><button class="primary" data-action="add-transaction">+ Add transaction</button></div><div id="transaction-list">${txnList(state.transactions, true)}</div></section>`;
}
function budgets() {
  return `<div class="dashboard-grid"><section class="card"><div class="card-head"><h2>${escape(monthTitle())}</h2><button class="small" data-action="add-category">+ Category</button></div>${state.summary.categories.map((c) => `<form class="budget-editor" data-budget="${escape(c.id)}"><label>${escape(c.name)}<input name="amount" inputmode="decimal" type="text" value="${(c.limit_cents / 100).toFixed(2)}" pattern="[0-9]+([.][0-9]{1,2})?" required aria-label="${escape(c.name)} monthly budget in ${escape(state.currency)}"></label><button type="submit">Save</button></form>`).join("")}</section><div class="stack"><section class="card"><h2>Plan, then adjust.</h2><p class="muted">These limits belong to ${escape(monthTitle())}. Change the month to set a different plan.</p><p class="note">Amounts are in ${escape(state.currency)}. Zero means no budget has been allocated. Unused budgets do not roll over automatically.</p></section><section class="card"><h2>Budget progress</h2>${budgetRows()}</section></div></div>`;
}
function connections() {
  return `${installGuide()}<div class="provider-grid section-gap"><section class="card"><div class="provider-mark">Plaid</div><h2>Everyday banking</h2><p>Import bank and card transactions. Review categories after syncing.</p><p class="note">${state.providers.plaid ? `Configured · ${escape(state.providers.plaidEnvironment)}` : "Add your own keys in personal mode. Sandbox is the default."}</p><button data-action="plaid-connect" ${!state.providers.plaid ? "disabled" : ""}>Connect a bank</button></section><section class="card"><div class="provider-mark">SnapTrade</div><h2>Your investments</h2><p>Read investment account values through the connection portal.</p><p class="note">${state.providers.snaptrade ? "Configured · read-only portal" : "Personal or Commercial keys supported. No trading routes."}</p><button data-action="snaptrade-connect" ${!state.providers.snaptrade ? "disabled" : ""}>Connect investments</button></section><section class="card"><div class="provider-mark">Ollama</div><h2>Optional local AI</h2><p>Ask open-ended questions using a locally downloaded model.</p><p class="note">${state.providers.ai ? "Enabled · sends your question and category totals to local Ollama." : "Off by default. The assistant can still show deterministic summaries."}</p><button data-page="chat">Open assistant →</button></section></div><section class="card section-gap"><div class="card-head"><h2>Connection status</h2><button class="small" data-action="refresh">Refresh view</button></div>${state.connections.length ? state.connections.map((c) => `<div class="connection-row"><div><strong>${escape(c.provider === "plaid" ? "Bank connection" : "Investment connection")}</strong><small>Status: ${escape(c.status)} · Last successful import: ${escape(c.synced_at ? new Date(c.synced_at).toLocaleString() : "Not yet synced")}</small></div><button class="small" data-sync="${escape(c.id)}" data-provider="${escape(c.provider)}">Sync data</button></div>`).join("") : '<p class="empty">No live connections yet. Your manual budget works on its own.</p>'}<p class="footer-note">Sync imports provider-cached data. It does not force a paid institution refresh. Reconnect using the provider portal if authorization expires.</p></section><section class="card section-gap"><h2>Investment accounts</h2>${state.investments.length ? state.investments.map((a) => `<div class="connection-row"><div><strong>${escape(a.name)}</strong><small>${escape(a.status)} · Last import ${escape(new Date(a.synced_at).toLocaleString())}</small></div><strong>${a.value_cents === null ? "Unavailable" : money(a.value_cents)}</strong></div>`).join("") : '<p class="empty">Investment values will appear after a successful sync.</p>'}<p class="footer-note">Investment account values are shown separately from budget cash flow. Missing data is unavailable; previously imported values can be stale. No currency conversion or total net-worth calculation is performed.</p></section>`;
}
function clearChat() {
  clearTimeout(historyTimer);
  messages = [];
  conversations = [];
  activeConversation = null;
  chatDrafts = {};
  chatEpoch++;
  chatBusy = false;
  historyOpen = false;
  historyArchived = false;
  conversationBefore = null;
  conversationNext = null;
}
async function loadConversations(offset = 0) {
  const epoch = chatEpoch;
  const r = await api(
    `/api/conversations?archived=${historyArchived ? 1 : 0}&offset=${offset}`,
  );
  if (epoch !== chatEpoch || !state) return;
  conversations = offset ? [...conversations, ...r.threads] : r.threads;
  conversationNext = r.next;
}
async function readConversation(id, older = false) {
  const epoch = chatEpoch;
  const r = await api(
    `/api/conversations/${id}${older ? `?before=${conversationBefore}` : ""}`,
  );
  if (epoch !== chatEpoch || !state) return;
  activeConversation = r.thread;
  messages = older ? [...r.turns, ...messages] : r.turns;
  conversationBefore = r.before;
  chatBusy = messages.some((t) => t.state === "running");
  scheduleHistory();
}
function scheduleHistory() {
  clearTimeout(historyTimer);
  if (!chatBusy || !activeConversation || !state) return;
  const id = activeConversation.id;
  historyTimer = setTimeout(async () => {
    if (!state || activeConversation?.id !== id) return;
    if (document.hidden) {
      scheduleHistory();
      return;
    }
    try {
      await readConversation(id);
      if (page === "chat") render();
    } catch (e) {
      notice(e.message);
      if (state) scheduleHistory();
    }
  }, 1800);
}
function chat() {
  const controls = `<div class="chat-tools"><button data-action="chat-history">Conversations</button><button data-action="chat-new" ${chatBusy ? "disabled" : ""}>New chat</button></div>`;
  if (historyOpen)
    return `<section class="card chat">${controls}<h2>Conversations</h2><button data-action="chat-archived">${historyArchived ? "Show active" : "Show archived"}</button>${conversations.map((t) => `<button class="history-row" data-conversation="${escape(t.id)}"><strong>${t.pinned ? "★ " : ""}${escape(t.title)}</strong><small>${escape(new Date(t.updated_at).toLocaleString())}</small></button>`).join("") || "<p>No saved conversations yet.</p>"}${conversationNext !== null ? '<button data-action="chat-more">More conversations</button>' : ""}</section>`;
  return `<section class="card chat">${controls}${activeConversation ? `<h2>${escape(activeConversation.title)}</h2><details><summary>Manage conversation</summary><div class="chat-tools"><button data-action="chat-rename" ${chatBusy ? "disabled" : ""}>Rename</button><button data-action="chat-pin" ${chatBusy ? "disabled" : ""}>${activeConversation.pinned ? "Unpin" : "Pin"}</button><button data-action="chat-archive" ${chatBusy ? "disabled" : ""}>${activeConversation.archived ? "Restore" : "Archive"}</button><button data-action="chat-delete">Delete</button></div></details>` : "<h2>Ask about your budget</h2>"}<p class="note">Saved on your server until deleted. Each answer reflects its original budget month. ${state.providers.ai ? "Your question and category totals go to local Ollama." : "No AI service is needed for a budget summary."}</p>${!messages.length ? '<div class="suggestions"><button data-question="How much budget do I have left?">How much budget is left?</button><button data-question="Summarize my cash flow this month.">Summarize my cash flow</button></div>' : ""}<div class="messages" role="log" aria-live="polite">${conversationBefore ? '<button data-action="chat-older">Earlier messages</button>' : ""}${messages.map((t) => `<div class="chat-turn"><small>${escape(new Date(t.created_at).toLocaleString())} · Budget month ${escape(t.context.month)}</small><div class="message user"><small>You</small>${escape(t.question)}</div>${t.reply ? `<div class="message"><small>${t.reply.mode === "ollama" ? "Local AI" : "Budget summary"}</small>${escape(t.reply.answer)}</div>` : ""}${t.state === "running" ? '<p role="status">Preparing your answer. You can return later.</p>' : ""}${["failed", "interrupted"].includes(t.state) ? `<p>${t.state === "interrupted" ? "This reply was interrupted by a restart and was not automatically retried." : "This reply could not finish. Your question is saved."}</p><button data-retry="${escape(t.id)}" ${chatBusy ? "disabled" : ""}>Ask again</button>` : ""}</div>`).join("")}</div><form id="chat-form"><label><span class="sr-only">Ask about your budget</span><textarea name="question" placeholder="Ask about your budget…" maxlength="1200" required ${activeConversation?.archived ? "disabled" : ""}>${escape(chatDrafts[activeConversation?.id || "new"] || "")}</textarea></label><button class="primary" type="submit" ${chatBusy || activeConversation?.archived ? "disabled" : ""}>Ask →</button></form><p class="note">Read-only answers. No account credentials, bank transactions, or merchant names are supplied by the app to the assistant. Each question uses that month’s aggregates; previous messages are saved for reading, not sent to Ollama. Replies never change your budget.</p></section>`;
}
function openDialog(title, content) {
  dialog.innerHTML = `<div class="dialog-head"><h2 id="editor-title">${escape(title)}</h2><button class="ghost" type="button" data-action="close-dialog" aria-label="Close dialog">${icon("close")}</button></div>${content}<p id="dialog-error" role="alert" class="dialog-error"></p>`;
  dialog.showModal();
}
async function ask(question) {
  if (chatBusy) return;
  const epoch = chatEpoch;
  chatBusy = true;
  try {
    if (!activeConversation)
      activeConversation = await api("/api/conversations", "POST", {
        id: crypto.randomUUID(),
      });
    const id = activeConversation.id;
    const payload = {
      question,
      month: selectedMonth,
      revision: activeConversation.revision,
      requestId: crypto.randomUUID(),
    };
    try {
      await api(`/api/conversations/${id}/messages`, "POST", payload);
    } catch (e) {
      if (!(e instanceof TypeError)) throw e;
      await api(`/api/conversations/${id}/messages`, "POST", payload);
    }
    if (epoch !== chatEpoch || !state) return;
    chatDrafts[id] = "";
    chatDrafts.new = "";
    await readConversation(id);
    await loadConversations();
  } catch (e) {
    notice(e.message);
    if (epoch === chatEpoch && state) {
      chatBusy = false;
      if (activeConversation)
        try {
          await readConversation(activeConversation.id);
        } catch {}
    }
  } finally {
    if (epoch === chatEpoch && state && page === "chat") render();
  }
}
async function plaidConnect() {
  const { link_token } = await api("/api/providers/plaid/link", "POST", {});
  if (!window.Plaid)
    await new Promise((resolve, reject) => {
      const script = document.createElement("script");
      script.src = "https://cdn.plaid.com/link/v2/stable/link-initialize.js";
      const timer = setTimeout(
        () => reject(new Error("Plaid Link timed out. Try connecting again.")),
        15000,
      );
      script.onload = () => {
        clearTimeout(timer);
        resolve();
      };
      script.onerror = () => {
        clearTimeout(timer);
        reject(new Error("Plaid Link could not load"));
      };
      document.head.append(script);
    });
  const handler = window.Plaid.create({
    token: link_token,
    onSuccess: async (public_token) => {
      try {
        await api("/api/providers/plaid/exchange", "POST", { public_token });
        await load();
        notice("Bank connected. Use Sync data to import transactions.");
      } catch (e) {
        notice(e.message);
      } finally {
        handler.destroy();
      }
    },
    onExit: (error) => {
      if (error) notice("Bank connection was not completed. Try again.");
      handler.destroy();
    },
  });
  handler.open();
}
document.addEventListener("click", async (event) => {
  const button = event.target.closest("button");
  if (!button) return;
  if (button.dataset.page) {
    page = button.dataset.page;
    if (page === "chat")
      try {
        await loadConversations();
        if (!activeConversation && conversations.length)
          await readConversation(conversations[0].id);
      } catch (e) {
        notice(e.message);
      }
    if (state) render();
    document.querySelector("#main")?.focus({ preventScroll: true });
    return;
  }
  if (button.dataset.question) {
    await ask(button.dataset.question);
    return;
  }
  if (button.dataset.conversation) {
    chatEpoch++;
    historyOpen = false;
    try {
      await readConversation(button.dataset.conversation);
      render();
    } catch (e) {
      notice(e.message);
    }
    return;
  }
  if (button.dataset.retry) {
    const t = messages.find((t) => t.id === button.dataset.retry);
    if (t && confirm("Send this question again as a new assistant request?"))
      await ask(t.question);
    return;
  }
  const action = button.dataset.action;
  button.disabled = true;
  try {
    if (action?.startsWith("chat-")) {
      if (action === "chat-history") {
        historyOpen = !historyOpen;
        await loadConversations();
      }
      if (action === "chat-archived") {
        historyArchived = !historyArchived;
        await loadConversations();
      }
      if (action === "chat-more") await loadConversations(conversationNext);
      if (action === "chat-older")
        await readConversation(activeConversation.id, true);
      if (action === "chat-new") {
        activeConversation = await api("/api/conversations", "POST", {
          id: crypto.randomUUID(),
        });
        messages = [];
        conversationBefore = null;
        historyOpen = false;
        chatBusy = false;
        await loadConversations();
      }
      if (action === "chat-rename") {
        openDialog(
          "Rename conversation",
          `<form id="chat-name-form"><label>Conversation title<input name="title" maxlength="100" value="${escape(activeConversation.title)}" required></label><button class="primary">Save name</button></form>`,
        );
        return;
      }
      if (action === "chat-pin" || action === "chat-archive")
        activeConversation = await api(
          `/api/conversations/${activeConversation.id}`,
          "PATCH",
          {
            revision: activeConversation.revision,
            ...(action === "chat-pin"
              ? { pinned: !activeConversation.pinned }
              : { archived: !activeConversation.archived }),
          },
        );
      if (
        action === "chat-delete" &&
        confirm(
          `Delete “${activeConversation.title}” and all its messages? This cannot be undone.`,
        )
      ) {
        await api(
          `/api/conversations/${activeConversation.id}/delete`,
          "POST",
          {},
        );
        delete chatDrafts[activeConversation.id];
        activeConversation = null;
        messages = [];
        chatBusy = false;
        historyOpen = true;
        await loadConversations();
      }
      if (state) render();
      return;
    }
    if (action === "logout") {
      await api("/api/logout", "POST", {});
      state = null;
      clearChat();
      await loginScreen();
    }
    if (action === "close-dialog") dialog.close();
    if (action === "refresh") await load();
    if (action === "add-category")
      openDialog(
        "Add a budget category",
        `<form id="category-form" class="form-stack"><label>Category name<input name="name" maxlength="40" required placeholder="e.g. Travel"></label><button class="primary" type="submit">Add category</button></form>`,
      );
    if (action === "add-transaction")
      openDialog(
        "Add a transaction",
        `<form id="transaction-form" class="form-stack"><label>Description<input name="description" maxlength="160" required placeholder="What was it for?"></label><div class="field-grid"><label>Date<input name="date" type="date" value="${selectedMonth}-01" required></label><label>Amount (${escape(state.currency)})<input name="amount" inputmode="decimal" type="text" pattern="-?[0-9]+([.][0-9]{1,2})?" required placeholder="0.00"></label></div><label>Category<select name="category_id">${categoryOptions()}</select></label><p class="note">Positive = money out. Negative = money in. Choose Income for pay, an expense category for refunds, or Transfers for moving your own money.</p><button class="primary" type="submit">Add transaction</button></form>`,
      );
    if (action === "plaid-connect") await plaidConnect();
    if (action === "snaptrade-connect") {
      const { url } = await api("/api/providers/snaptrade/connect", "POST", {});
      openDialog(
        "Connect your investments",
        `<p>Open the read-only SnapTrade portal, complete the connection, then return here and sync your data.</p><a href="${escape(url)}" target="_blank" rel="noopener noreferrer">Open SnapTrade portal →</a>`,
      );
      await load();
    }
    if (button.dataset.sync) {
      await api(`/api/providers/${button.dataset.provider}/sync`, "POST", {
        id: button.dataset.sync,
      });
      await load();
      notice("Import finished. Review the latest data and categories.");
    }
    if (button.dataset.review) {
      await api("/api/transactions/category", "PATCH", {
        id: button.dataset.review,
        category_id: button.dataset.category,
      });
      await load();
      notice("Category reviewed.");
    }
  } catch (e) {
    notice(e.message);
  } finally {
    button.disabled = false;
  }
});
document.addEventListener("submit", async (event) => {
  event.preventDefault();
  const form = event.target,
    data = Object.fromEntries(new FormData(form));
  const button = form.querySelector('button[type="submit"]');
  if (button) button.disabled = true;
  try {
    if (form.id === "login-form") {
      await api("/api/login", "POST", data);
      await load();
    }
    if (form.id === "category-form") {
      await api("/api/categories", "POST", data);
      dialog.close();
      await load();
      notice("Category added.");
    }
    if (form.id === "transaction-form") {
      await api("/api/transactions", "POST", data);
      dialog.close();
      await load();
      notice("Transaction added.");
    }
    if (form.dataset.budget) {
      await api("/api/budgets", "PUT", {
        month: selectedMonth,
        category_id: form.dataset.budget,
        amount: data.amount,
      });
      await load();
      notice("Monthly budget saved.");
    }
    if (form.id === "chat-name-form") {
      activeConversation = await api(
        `/api/conversations/${activeConversation.id}`,
        "PATCH",
        { revision: activeConversation.revision, title: data.title },
      );
      dialog.close();
      await loadConversations();
      render();
    }
    if (form.id === "chat-form") await ask(data.question);
  } catch (e) {
    const error =
      form.id === "login-form"
        ? document.querySelector("#login-error")
        : dialog.open
          ? document.querySelector("#dialog-error")
          : null;
    if (error) error.textContent = e.message;
    else notice(e.message);
  } finally {
    if (button) button.disabled = false;
  }
});
document.addEventListener("change", async (event) => {
  const target = event.target;
  try {
    if (target.id === "month") {
      if (!target.value) return;
      selectedMonth = target.value;
      await load();
    }
    if (target.dataset.transaction) {
      await api("/api/transactions/category", "PATCH", {
        id: target.dataset.transaction,
        category_id: target.value,
      });
      await load();
      notice("Category updated.");
    }
  } catch (e) {
    notice(e.message);
  }
});
document.addEventListener("input", (event) => {
  if (event.target.matches("#chat-form textarea"))
    chatDrafts[activeConversation?.id || "new"] = event.target.value;
  if (event.target.id === "search") {
    const q = event.target.value.toLowerCase();
    document.querySelector("#transaction-list").innerHTML = txnList(
      state.transactions.filter((t) =>
        `${t.description} ${state.categories.find((c) => c.id === t.category_id)?.name}`
          .toLowerCase()
          .includes(q),
      ),
      true,
    );
  }
});
load().catch(async (e) => {
  if (!document.querySelector("#login-form")) {
    await loginScreen();
    notice(e.message);
  }
});

// Keep the active chat composer reachable when a mobile keyboard changes the
// visual viewport. Never focus the input automatically or disable page zoom.
function fitChatViewport() {
  const vv = window.visualViewport;
  const input = document.activeElement;
  const composing = page === "chat" && input?.tagName === "TEXTAREA";
  const keyboardOpen =
    composing && vv && vv.scale === 1 && window.innerHeight - vv.height > 120;
  document.body.classList.toggle("keyboard-open", Boolean(keyboardOpen));
  if (keyboardOpen) input.scrollIntoView({ block: "nearest" });
}
window.visualViewport?.addEventListener("resize", fitChatViewport);
document.addEventListener("focusin", fitChatViewport);
document.addEventListener("focusout", () =>
  requestAnimationFrame(fitChatViewport),
);
